version: '3.1'

services:

  mongo:
    image: mongo:latest
    ports:
      - 27071:27071
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - ALLOW_EMPTY_PASSWORD=yes
