"""init_db

Revision ID: 64052ccd4f51
Revises: f9168636ecd4
Create Date: 2024-06-24 12:27:58.028789

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "64052ccd4f51"
down_revision: Union[str, None] = "f9168636ecd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
